# Generated by Django 5.1.4 on 2024-12-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
