# Generated by Django 5.1.4 on 2024-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_permission_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='avail_permission',
            field=models.FloatField(default=0.0),
        ),
    ]
